POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"Ex1GestaoAlunos",
  "port":1111,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type": "application/json"},
          "body":{"error":"idade minima n atingida"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos","method":"POST"}},
        {"equals":{"body":{"idade":8}}} 
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type": "application/json"},
          "body":{"error":"curso n encontrado"}
        }
      }],
      "predicates": [
        {"equals":{"path":"/api/alunos","method":"POST"}},
        {"contains":{"body":{"curso":"inexistente"}}} 
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"aluno add com sucesso","id":3}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"nome":"joao","idade":12,"curso":"ti"},
            {"id":2,"nome":"maria","idade":15,"curso":"design"}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"id":1,"nome":"joao","idade":12,"curso":"ti"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos/1","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"aluno 1 atualizado"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos/1","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"aluno n existe"}
          }
        }
      ],
      "predicates":[
        {"equals":{"path":"/api/alunos/2","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"aluno removido"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/alunos/1","method":"DELETE","headers":{"cargo":"Admin"}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":403,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"acesso negado,apenas administradores"}
        }
      }],
      "predicates":[
        {"equals":{"method":"DELETE"}}
      ]
    }
  ]
}


###


#listar todos os alunos
GET http://localhost:1111/api/alunos
Content-Type: application/json


###

#mostrar um aluno especifico
GET http://localhost:1111/api/alunos/1
Content-Type: application/json


###

#criar aluno com idd menor q 10 (Erro)
POST http://localhost:1111/api/alunos
Content-Type: application/json

{
  "nome":"pedro",
  "idade":8,
  "curso":"ti"
}


###

#criar aluno com curso inexistente (Erro)
POST http://localhost:1111/api/alunos
Content-Type: application/json

{
  "nome":"ana",
  "idade":14,
  "curso":"inexistente"
}


###

#criar aluno com dados corretos (Sucesso)
POST http://localhost:1111/api/alunos
Content-Type: application/json

{
  "nome":"carlos",
  "idade":12,
  "curso":"ti"
}


###

#atualizar aluno que existe (aluno 1)
PUT http://localhost:1111/api/alunos/1
Content-Type: application/json

{
  "nome":"joao",
  "idade":13,
  "curso":"ti"
}


###

#atualizar aluno que n existe (aluno 2)
PUT http://localhost:1111/api/alunos/2
Content-Type: application/json

{
  "nome":"maria",
  "idade":16,
  "curso":"design"
}

###

#apagar aluno sem ser Administrador (erro)
DELETE http://localhost:1111/api/alunos/1
Content-Type: application/json


###

#apagar aluno sendo administrador (Sucesso)
DELETE http://localhost:1111/api/alunos/1
Content-Type: application/json
cargo: Admin